### ISSUE TITLE
Is it possible to use ldapjs in browser?

### ISSUE THREAD

**Issue by ghost** [mcavage/node-ldapjs#101]
I'm not familiar with node, so I need a lot of code reading to get answer on my question. Any help would be appreciate.
In short,  I'd like to use ldapjs on client side, i.e. in browser. The only problem I can see now,  is direct connection to the ldap server, which in fact impossible due to security reason. But, we have web-sockets now, so creating a simple proxy on server-side, which would  handle client connections and  traverse them to the ldap-server.  AFAIK, web-sockets are good enough for transmission of raw data, so it shouldn't be a problem.
The question is, is there any node-specific parts inside of nodejs which cannot be fixed to run in the browser environment?

**Comment by timrobertson100** [comment]
I see this is 3 years old, but I have the same question. Is it still the case it can't run in the browser?
Thanks

**Comment by pfmooney** [comment]
Correct.  It's written to run in Node.js.
