### ISSUE TITLE
How do i bind the binddn in ldapjs to authenticate a user ..

### ISSUE THREAD

**Issue by narendrachoudhary** [mcavage/node-ldapjs#132]
I have following configuration and could you please let me know the how to use the ldapjs to authenticate ...

**Comment by mvgadagi** [comment]
@pfmooney  can you please help me with the code line ` cb(err === null, err);` What does it mean I am very new to node.js

**Comment by Monbrey** [comment]
@mvgadagi Its calling the cb function which is passed in as the third argument.
err === null will evaluate to either true or false if 'err' is set or not, then is passes 'err' as the actual error.

**Comment by mvgadagi** [comment]
@pfmooney Okay Thanks much!!

**Comment by ZYoussef** [comment]
hello everyone, 
i have the same topic to do but am a little bit confused. 
This program will be on a .js file and we should link it with a html file to get the data( username and password), isn't it ? 
thank you for you answer. 
if you have a complete example i would be pleased to try it. 
Thank you again.

**Comment by srikanth9010** [comment]
connect ETIMEDOUT 192.168.95.66:389
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)

i am using the above code which is given above . iam getting the following error please provide the solution for the above error.
