### ISSUE TITLE
Issue reading thumbnailPhoto from LDAP

### ISSUE THREAD

**Issue by lmusat** [mcavage/node-ldapjs#137]
Hi,

I am using the following code to extract the thumbnail photo of a user from LDAP:

var ldap = require('ldapjs');
var fs = require('fs');

var client = ldap.createClient({
  url: 'ldap://**someip**:389'
});

var user = "**someuser**"

var opts = {
  filter: '(sAMAccountName='+user+')',
  scope: 'sub'
};

client.search('OU=**someou**,DC=**somedc**,DC=com', opts, function(err, res) {
  //assert.ifError(err);

  res.on('searchEntry', function(entry) {
    var info = entry.object;
    console.log('entry: ' + info.dn);
    console.log('entry: ' + info.sn);
    console.log('entry: ' + info.givenName);
    console.log('entry: ' + info.title);
    console.log('entry: ' + info.memberOf);
    console.log('entry: ' + info.co);
    console.log('entry: ' + info.manager);
    console.log('entry: ' + info.mail);
    fs.writeFile("./public/images/photos/"+user+"Thumb.jpg", info.thumbnailPhoto, function(err) {
        if(err) {
        console.log("errror writing thumbnail: "+err);
        } else {
        console.log("thumbnail was saved!");
        }
        });
    //...

As it is it fails to write a proper image as it transforms some of the bytes to something else. Can someone help?
For example, the first 4 bytes get transform from:
ffd8 ffe0
to
efbf bdef bfbd efbf bdef bfbd

Thanks.

**Comment by pfeilbr** [comment]
Searched for a good deal of time on how to solve this before I found this which worked.  Thanks!

**Comment by Flos** [comment]
Why is this issue closed but not resolved? I struggled with the same issue. Thanks @emueller-sage and @lmusat for a solution. 

That issue should really be reopend until its resolved.

**Comment by tokidoki11** [comment]
Out of Curiosity tho

how could you access _vals via buffers?

As I see, the attribute value **a** is this

Attribute { type: 'displayName', _vals: [ <Buffer 41 73 61 6e 67> ] }
[ <Buffer 41 73 61 6e 67> ]
