### ISSUE TITLE
InvalidAsn1Error: Expected 0x2: got 0x1

### ISSUE THREAD

**Issue by johannish** [mcavage/node-ldapjs#142]
I'm experiencing this error after several minutes of a bad connection.  The LDAP server I'm connecting to successfully establishes a TCP connection (`connect` event is fired and `onConnect` executes, removing the `connectTimeout` timer), but then doesn't respond for about 7 minutes, at which point I experience one of two conditions:
1. The uncaught error in the title of this issue: `InvalidAsn1Error: Expected 0x2: got 0x1` or
2. This log output from my own bunyan-semi-compatible logger:
   `[TRACE] { '0': { err: { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } }, '1': 'error event: %s', '2': 'Error\n    at Socket.onError ...`
   `[TRACE] { '0': 'close event had_err=%s', '1': 'yes' }`

Condition (1), which causes my application to crash, is more common.  Here is a simplified excerpt of my code:

```
var client = ldap.createClient({
  url: 'ldap://oid:3061/',
  timeout: "2000",
  connectTimeout: "5000"
});

//...

client.bind('', '', function (err) { // anonymous bind
  if (err) {
    callback(err, null); // correctly returns `request timeout (client interrupt)`
    return;
  }
  //...
});
```

I can send you the wireshark output of this conversation, if you'd like.

One hack that solves this issue for me, but which is obviously incorrect, is to add `conn.destroy()` in `function onRequestTimeout()` (about line 868).

**Comment by ORESoftware** [comment]
I see this

```js
les/ldapjs/lib/client/client.js:1282:14\n    at Array.forEach (native)\n    at Client._onClose (/home/amills/AdminUI/node_modules/ldapjs/lib/client/client.js:1272:19)\n    at TLSSocket.g (events.js:260:16)\n    at emitOne (events.js:77:13)\n    at TLSSocket.emit (events.js:169:7)\n    at TCP._onclose (net.js:469:12)","time":"2016-03-24T03:01:39.750Z","src":{"file":"/home/amills/AdminUI/app.js","line":265},"v":0}
uncaughtException--->Error: read ECONNRESET
    at exports._errnoException (util.js:856:11)
    at TLSWrap.onread (net.js:544:26)
/home/amills/AdminUI/bin/www.js:17
        throw err; //this should crash the server
        ^

Error: read ECONNRESET
    at exports._errnoException (util.js:856:11)
    at TLSWrap.onread (net.js:544:26)
```

an ECONNRESET throws an uncatchable exception or should I be able to catch it somehow?
