### ISSUE TITLE
Filters match on attribute values only case-sensitively

### ISSUE THREAD

**Issue by raumkraut** [mcavage/node-ldapjs#156]
Many LDAP attributes (eg. cn, givenName) are defined as defaulting to case-insensitive when it comes to applying filters. However:

```
> ldap = require('ldapjs')
> filter = ldap.parseFilter('(cn=*bob*)')
> filter.matches({cn: 'bob'})
true
> filter.matches({cn: 'Bob'})
false
```

My suggestion:
* Make *all* filters case-__in__sensitive by default, since I suspect that is the most common use-case (it certainly is for me),
* Add an argument to ```filter.matches(...)``` (or when creating a ```Filter``` object) which allows us to indicate which attributes are case-sensitive.

**Comment by pfmooney** [comment]
Consumers can choose to implement their own schema rules by overriding filter match methods.

**Comment by alansouzati** [comment]
hi @pfmooney, can you provide directions on how to override the filter match methods?

**Comment by alansouzati** [comment]
this is what I had to do, I'm sure that has to be an easier way to accomplish this:

```javascript
import ldap from 'ldapjs';
import helpers from 'ldap-filter/lib/helpers';

function escapeRegExp(str) {
  /* JSSTYLED */
  return str.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, '\\$&');
}

ldap.SubstringFilter.prototype.matches = function (target, strictAttrCase) {
  var tv = helpers.getAttrValue(target, this.attribute, strictAttrCase);
  if (tv !== undefined && tv !== null) {
    var re = '';

    if (this.initial)
      re += '^' + escapeRegExp(this.initial) + '.*';
    this.any.forEach(function (s) {
      re += escapeRegExp(s) + '.*';
    });
    if (this.final)
      re += escapeRegExp(this.final) + '$';

    var matcher = new RegExp(re, 'i');
    return helpers.testValues(function (v) {
      return matcher.test(v);
    }, tv);
  }

  return false;
};
```

The only thing I had to change was `var matcher = new RegExp(re);` to `var matcher = new RegExp(re, 'i');`
