### ISSUE TITLE
SASL digest md5

### ISSUE THREAD

**Issue by DominicBoettger** [mcavage/node-ldapjs#170]
I am using ldapjs as a client library and like it a lot that it has no bindings to any system libraries.

Did somebody try to integrate https://github.com/jaredhanson/js-sasl-digest-md5 as authentication mechanism?

**Comment by JCarlos12** [comment]
does ldapjs now support sasl?

**Comment by kalebealvs** [comment]
Same question here.

**Comment by jsumners** [comment]
Potentially resolved by #473.
