### ISSUE TITLE
Ldap command injection?

### ISSUE THREAD

**Issue by gdw2** [mcavage/node-ldapjs#181]
It ldapjs susceptible to ldap injection of any sort?  For example, if a nodejs app takes input from a web for and uses it in a `client.search` command, it is conceivable that an attacker could craft a string that when put into the `client.search` command could actually end up deleting directory entries (even if the nodejs code never calls `client.del`)?

**Comment by shaozi** [comment]
when using `client.bind(dn, password, callback)`, and `dn` is a user input. Do I need to sanitize `dn`? If yes, how?

**Comment by jsumners** [comment]
@shaozi you could attempt to validate that the string passes validation for a proper `DN` string, but that'd be about all you can do. That's an exercise left up to you -- https://duckduckgo.com/?q=validate+ldap+dn&t=vivaldi&ia=web
