### ISSUE TITLE
Easier handling of objectGUID queries

### ISSUE THREAD

**Issue by davefinster** [mcavage/node-ldapjs#218]
With the addition of binary value queries in EqualityFilter, I've been using the below function to query for LDAP objects directly based on GUID.

Would it be possible to better integrate this into EqualityFilter as a special case when the attribute is objectGUID? At this stage, that would create a dependency on Attribute as that seems to be where the GUID formatting is stored. 

Alternatively just expose it initially as a utility function from the top of the module (namely index.js)?

```javascript
//format - the GUID formatting used when creating the string version 'data'
//data - the string version of the GUID 
function unformatGuid(format, data){
  var cleanData = data.replace(/-/g, "");
  var cleanFormat = format.replace(/[-\{]/g, "").split('}');
  var d = Array(16);
  for (var i = 0; i < cleanData.length; i = i + 2) {
    d[parseInt(cleanFormat[i/2])] = cleanData[i] +  cleanData[i+1];
  }
  return new Buffer(d.join(''), 'hex');
}
//example
var guidBuffer = unformatGuid(ldap.GUID_FORMAT_D, 'a99734ce-3379-4e29-a9bf-68234f775768')
var f = new equalityFilter({
    attribute: 'objectGUID',
    value: guidBuffer
});
```

**Comment by pfmooney** [comment]
I've decided to rip the special treatment of objectGUID completely out.  Special handling for attributes like that can be left up to something specific to the service being accessed.
