### ISSUE TITLE
Octet and Directory String in Active Directory

### ISSUE THREAD

**Issue by magmel48** [mcavage/node-ldapjs#228]
Guys, you developed perfect library for node.js! But I found one issue, ldapjs can't recognize difference between Octet and Directory String and make utf-string, not array.

My code: https://gist.github.com/magmel48/114a17228e35761d6efc
AD values: 
![untitled-1](https://cloud.githubusercontent.com/assets/5560490/4384700/80a7e360-43ba-11e4-8e7a-09a8031d6416.jpg)

Response from my code (I tried to get objectGUID value):
![untitled-2](https://cloud.githubusercontent.com/assets/5560490/4384702/8edefce8-43ba-11e4-9ae5-16fee4e4dc25.jpg)

**Comment by Predhin** [comment]
+1 had a similar issue retrieving thumbnailPhoto attribute, wherein I was using entry.object in which I was getting a corrupted buffer. But when I used the  entry.raw everything starting working great. Thanks @pfmooney and @magmel48.
