### ISSUE TITLE
SSL connection fails using Node 0.12

### ISSUE THREAD

**Issue by feisley** [mcavage/node-ldapjs#256]
When making a SSL connection using Node 0.12 the connection fails with the following error:

```
/Users/developer/node_modules/ldapjs/lib/client/client.js:111
  closeSocket.on('close', function onClose(had_err) {
             ^
TypeError: Cannot read property 'on' of undefined
    at setupSocket (/Users/developer/node_modules/ldapjs/lib/client/client.js:111:14)
    at Client._connect (/Users/developer/node_modules/ldapjs/lib/client/client.js:742:3)
    at new Client (/Users/developer/node_modules/ldapjs/lib/client/client.js:247:22)
    at Object.createClient (/Users/developer/node_modules/ldapjs/lib/client/index.js:60:12)
    at Object.<anonymous> (/Users/developer/devel/ldap/ldap.js:2:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

This did not occur in 0.10 and the client works as expected if Node is downgraded. Additionally this has been tested against node-ldapjs current release from NPM (0.7.1) as well as the current master branch.

**Comment by 1j01** [comment]
:+1:

**Comment by 1j01** [comment]
This is fixed in master, right?

**Comment by qrpike** [comment]
I'm getting the same error still.. Has this been fixed?

**Comment by 1j01** [comment]
I guess I just assumed since I didn't find the line of code that was failing in master. The relevant code is now here: https://github.com/mcavage/node-ldapjs/blob/773a1c6fd20ca50174a5a82ec61b84361f51f81c/lib/client/client.js#L1015-L1016

**Comment by pfmooney** [comment]
This should be fix in 0.8.  See #270.

**Comment by diversario** [comment]
Ok, great to see it's fixed. Looking at the blockers list they're all closed. Is 0.8 coming to npm sometime soon?

**Comment by mayur-arora** [comment]
Is the next -version coming out soon ?

**Comment by mayur-arora** [comment]
@pfmooney any chance you could point us to the fix for this issue https://github.com/mcavage/node-ldapjs/issues/256  ?
 
I can't use an unregistered npm package of ldapjs. Maybe , I can make this change in 0.7.1

**Comment by KrisSiegel** [comment]
It's been 6 months and this is still closed due to it being fixed in a release that doesn't yet exist. Shouldn't this be open until it's really resolved?

**Comment by diversario** [comment]
This is fixed in https://www.npmjs.com/package/ldapjs-hotfix, FYI.

**Comment by KrisSiegel** [comment]
Well that would have been better put into a point release for ldapjs but it makes life easier; thanks!

**Comment by diversario** [comment]
Yep, so we're using that until `ldapjs` is fixed.
