### ISSUE TITLE
Cannot set guid_format?

### ISSUE THREAD

**Issue by tstiemerling** [mcavage/node-ldapjs#275]
Just recently started seeing this (using 0.7.1):

ldapjs.Attribute.settings.guid_format = ldapjs.GUID_FORMAT_D;
                                      ^
TypeError: Cannot set property 'guid_format' of undefined

Any ideas?

**Comment by pfmooney** [comment]
If you're using #master (not 0.7.1), the GUID formatting logic has been pulled out of ldapjs.

**Comment by pfmooney** [comment]
See #218.  This will be on the list of breaking changes for 0.7.1 -> 0.8.0.

**Comment by tstiemerling** [comment]
Odd - when I use the npm release - which gets version 0.7.1, the guid stuff is not there either - and yes, we have been using master up to now.

**Comment by pfmooney** [comment]
The git version might be cached in the node_modules dir, or something like that.

**Comment by srikanth9010** [comment]
i am facing the same issuse please provide the solution for this?

**Comment by UziTech** [comment]
@srikanth9010 If you create a new issue and give us some code, the version you are using, and the exact error you are getting we can try to help you.
