### ISSUE TITLE
[Error: Cannot find module './DTraceProviderBindings'] 

### ISSUE THREAD

**Issue by bobchennan** [mcavage/node-ldapjs#64]
I'm using Ubuntu 11.10, and when I use ldapjs, there is always an error:

---

_[Error: Cannot find module './DTraceProviderBindings']_

---

How can I fix it? What can DTraceProvider do just in ldapjs?

Thanks a lot.

**Comment by damienstanton** [comment]
This issue is also occurring on Meteor 1.0.3.2 / OS X 10.10 when installed via the typ:accounts-ldap package (which wraps ladpjs)

**Comment by Benco1** [comment]
Same. Error still present through Meteor typ:accounts-ldap package. Why (still) an error for an optional module? No clean solution for this yet?

**Comment by lukebrdn** [comment]
Reinstalling restify fixed it for me.

**Comment by antonioortegajr** [comment]
Reinstalling restify fixed it for me as well.
