### ISSUE TITLE
Default handler for all extended operations

### ISSUE THREAD

**Issue by kd42** [mcavage/node-ldapjs#98]
I'd really like to have a handler that would grab all the extended operations, not just a specific one with the matching name.

**Comment by ptusch** [comment]
Hello,

it really smells like I'd be correct with my question in here.
Does the current exop implementation allows a combination with a modification operation?

I try to accomplish to update an LDAP entry and get another value out of it in one call.
E.g.: I try to get the latest modify timestamp after I modified an attribute.
I'd write something like this:

`ldapmodify -e'!postread=modifyTimestamp' -D [LOGINNAME] -w [PASS] -H [LDAP HOST]`
< Then I type in my ldif >
```
dn: [DN TO TARGET OBJECT]
changetype: modify
replace: name
name: walter
```

< OUTPUT >
```modifying entry "[DN]"
control: 1.3.6.1.1.13.2 ...
'# ==> postread
dn: [DN]
name: walter
modifyTimestamp: 20160215145653Z
'# <== postread
```

Is this possible with ldapjs?

Best regards,
Philipp
