### ISSUE TITLE
res.on("searchEntry") in next.js after build does not return data.

### ISSUE THREAD

**Issue by pbukel** [mcavage/node-ldapjs#982]
I have an issue getting user data from AD using res.on("searchEntry"). I have described it more here:
https://stackoverflow.com/questions/78448023/res-onsearchentry-from-ldap-js-does-not-returns-result-in-next-js-production

It work in dev mode, but not after the build. After some research, I have placed a delay 20sec before resolving data from res.on("searchEntry") - in case it delays... but I have noticed That it not receiving anything. Replies only get on :
res.on("searchRequest", (searchRequest) => {
          console.log("65", searchRequest.messageId);
        });
and after on : 
res.on("end", async (result) => {
          //   console.log(result);
          resolve({ userData }); - this I am setting exactly when I get res.on("searchEntry") result.
          client.destroy();
        });
 res.on("searchEntry").- never get reply. BUT it gets when next.js is in dev mode.... How res.on("searchEntry") - work? what can cause, that we don't get a reply on this request from LDAP?  Kind of URL setup maybe?  I am testing on localhost.
 Does res.on("end", async (result))  REUSLT contain result from searchEntry ? 
 Appreciate for help on this!

**Comment by jsumners** [comment]
We do not support bundling of any sort.
