### ISSUE TITLE
While installing the ldapjs i get this following error, not sure ain't it's ldap or npm

### ISSUE THREAD

**Issue by muraray** [mcavage/node-ldapjs#99]
npm http GET https://registry.npmjs.org/abbrev

> buffertools@1.1.0 install D:\Node\apps\ldapjs-source\node_modules\buffertools
> node-gyp rebuild

D:\Node\apps\ldapjs-source\node_modules\buffertools>node "C:\Program Files (x86)
\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-
gyp.js" rebuild

> dtrace-provider@0.2.1 install D:\Node\apps\ldapjs-source\node_modules\dtrace-p
> rovider
> node-gyp rebuild

D:\Node\apps\ldapjs-source\node_modules\dtrace-provider>node "C:\Program Files (
x86)\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\n
ode-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files (x86)\nodejs\node_modules\n
pm\node_modules\node-gyp\lib\configure.js:109:14)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_module
s\node-gyp\lib\configure.js:78:11
gyp ERR! stack     at Object.oncomplete (fs.js:297:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files (x86)\nodejs\node_modules\npm\nod
e_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Node\apps\ldapjs-source\node_modules\buffertools
gyp ERR! node -v v0.8.14
gyp ERR! node-gyp -v v0.7.1
gyp ERR! not ok
npm http GET https://registry.npmjs.org/slide
npm http GET https://registry.npmjs.org/runforcover
npm http GET https://registry.npmjs.org/difflet
npm http GET https://registry.npmjs.org/deep-equal
npm http GET https://registry.npmjs.org/buffer-equal
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/nopt
npm ERR! buffertools@1.1.0 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the buffertools@1.1.0 install script.
npm ERR! This is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls buffertools
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program File
s (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! cwd D:\Node\apps\ldapjs-source
npm ERR! node -v v0.8.14
npm ERR! npm -v 1.1.65
npm ERR! code ELIFECYCLE
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files (x86)\nodejs\node_modules\n
pm\node_modules\node-gyp\lib\configure.js:109:14)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_module
s\node-gyp\lib\configure.js:78:11
gyp ERR! stack     at Object.oncomplete (fs.js:297:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files (x86)\nodejs\node_modules\npm\nod
e_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Node\apps\ldapjs-source\node_modules\dtrace-provider
gyp ERR! node -v v0.8.14
gyp ERR! node-gyp -v v0.7.1
gyp ERR! not ok
npm http GET https://registry.npmjs.org/vasync/1.3.2

between abbrev node_module -> vasync module.

**Comment by anirbangithub** [comment]
Hi muraray how did you set Python Path as default? please help.
